In [44]:
import numpy as np

# Numpy Basics


NumPy provides an N-dimensional array type, the ndarray.  
It describes a collection of “items” of the _same_ type.  
The items can be indexed using for example N integers.  
All ndarrays are homogeneous: every item takes up the same size block of memory.  
An item from the array is represented by a PyObject which is one of the built in NumPy scalar types.


<p align="left">
<img src="https://numpy.org/doc/stable/_images/threefundamental.png">
</p>


## NumPy Array Attributes


In [45]:
np.random.seed(0)

In [46]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

## Array Indexing and Slicing

Array indexing refers to any use of the square brackets ([]) to index array values.  
There are many options to indexing, which give numpy indexing great power.

Most of the following examples show the use of indexing when referencing data in an array.  
The examples work just as well when assigning to an array.

Note: Slices of arrays do not copy the internal array data but only produce new views of the data.


![](../media/np_matrix_indexing.png)


In [47]:
x = np.array([[1, 2], [3, 4], [5, 6]])

array_info(x)

ndim: 2
shape: (3, 2)
size: 6
dtype: int32
values:
[[1 2]
 [3 4]
 [5 6]]



In [48]:
print(x[:3])

[[1 2]
 [3 4]
 [5 6]]


In [49]:
print(x[1:])

[[3 4]
 [5 6]]


In [50]:
print(x[1:2])

[[3 4]]


In [51]:
print(x[::-1])

[[5 6]
 [3 4]
 [1 2]]


In [52]:
print(x[0, :])

[1 2]


In [53]:
print(x[0])

[1 2]


In [54]:
print(x[:, 0])

[1 3 5]


In [55]:
mean = [0, 0]
cov = [[1, 2], [2, 5]]

x = np.random.multivariate_normal(
    mean=mean,
    cov=cov,
    size=10,
)

print(x)
print(x.shape)

[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]
(10, 2)


In [56]:
rand_idxs = np.random.randint(
    low=0,
    high=x.shape[0],
    size=3,
)

print(rand_idxs)

[9 9 0]


In [57]:
x_subsample = x[rand_idxs, :]

print(x_subsample)

[[ 0.03761145 -0.8336645 ]
 [ 0.03761145 -0.8336645 ]
 [-1.78290539 -3.87118733]]


In [58]:
x_subsample = x[rand_idxs]

print(x_subsample)

[[ 0.03761145 -0.8336645 ]
 [ 0.03761145 -0.8336645 ]
 [-1.78290539 -3.87118733]]


## Subarrays are views


In [59]:
print(x)

[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]


In [60]:
x_sub_array = x[:2, :2]

array_info(x_sub_array)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]]



In [61]:
x_sub_array[0, 0] = -1

array_info(x_sub_array)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [62]:
array_info(x)

ndim: 2
shape: (10, 2)
size: 20
dtype: float64
values:
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]



## Creating copies of arrays


In [63]:
x_copy = x[:2, :2].copy()

array_info(x_copy)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [64]:
x_copy[0, 0] = 42

array_info(x_copy)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[42.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [65]:
array_info(x)

ndim: 2
shape: (10, 2)
size: 20
dtype: float64
values:
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]



## Reshaping of Arrays


In [66]:
a = np.arange(
    start=1,
    stop=10,
)

array_info(a)

ndim: 1
shape: (9,)
size: 9
dtype: int32
values:
[1 2 3 4 5 6 7 8 9]



In [67]:
grid = np.reshape(
    a,
    newshape=(3, 3),
)

array_info(grid)

ndim: 2
shape: (3, 3)
size: 9
dtype: int32
values:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [68]:
x = np.array([1, 2, 3])

array_info(x)

ndim: 1
shape: (3,)
size: 3
dtype: int32
values:
[1 2 3]



In [69]:
x = np.reshape(
    x,
    newshape=(1, 3),
)

array_info(x)

ndim: 2
shape: (1, 3)
size: 3
dtype: int32
values:
[[1 2 3]]



In [70]:
array_info(x)

x = x[np.newaxis, :]

array_info(x)

ndim: 2
shape: (1, 3)
size: 3
dtype: int32
values:
[[1 2 3]]

ndim: 3
shape: (1, 1, 3)
size: 3
dtype: int32
values:
[[[1 2 3]]]



In [71]:
array_info(x)

x = x.reshape((3, 1))

array_info(x)

ndim: 3
shape: (1, 1, 3)
size: 3
dtype: int32
values:
[[[1 2 3]]]

ndim: 2
shape: (3, 1)
size: 3
dtype: int32
values:
[[1]
 [2]
 [3]]



In [72]:
array_info(x)

x = x.ravel()

array_info(x)

ndim: 2
shape: (3, 1)
size: 3
dtype: int32
values:
[[1]
 [2]
 [3]]

ndim: 1
shape: (3,)
size: 3
dtype: int32
values:
[1 2 3]



In [73]:
x = x.reshape((3, 1))
array_info(x)

x = x.flatten()

array_info(x)

ndim: 2
shape: (3, 1)
size: 3
dtype: int32
values:
[[1]
 [2]
 [3]]

ndim: 1
shape: (3,)
size: 3
dtype: int32
values:
[1 2 3]



### “Automatic” Reshaping


In [74]:
a = np.arange(30)

array_info(a)

ndim: 1
shape: (30,)
size: 30
dtype: int32
values:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]



In [75]:
b = a.reshape((2, -1, 3))

array_info(b)

ndim: 3
shape: (2, 5, 3)
size: 30
dtype: int32
values:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]



## Changing the Dtype

### Integer Types

| Numpy type   | C type   | Description                            |
| ------------ | -------- | -------------------------------------- |
| numpy.int8   | int8_t   | Byte ($-2^{7}$ to ($2^{7} - 1$))       |
| numpy.int16  | int16_t  | Integer ($-2^{15}$ to ($2^{15} - 1$))  |
| numpy.int32  | int32_t  | Integer ($-2^{31}$ to ($2^{31} - 1$))  |
| numpy.int64  | int64_t  | Integer ($-2^{63}$ to ($2^{63} - 1$))  |
| numpy.uint8  | uint8_t  | Unsigned integer (0 to ($2^{8} - 1$))  |
| numpy.uint16 | uint16_t | Unsigned integer (0 to ($2^{16} - 1$)) |
| numpy.uint32 | uint32_t | Unsigned integer (0 to ($2^{32} - 1$)) |
| numpy.uint64 | uint64_t | Unsigned integer (0 to ($2^{64} - 1$)) |

### Float Types

| Numpy type       | C type         |
| ---------------- | -------------- |
| numpy.float32    | float          |
| numpy.float64    | double         |
| numpy.complex64  | float complex  |
| numpy.complex128 | double complex |


In [76]:
x = np.float32([-1.0, 2.0, 3.0])

array_info(x)

ndim: 1
shape: (3,)
size: 3
dtype: float32
values:
[-1.  2.  3.]



In [77]:
x = np.array(
    [-1.0, 2.0, 3.0],
    dtype=np.float32,
)

In [78]:
y = x.astype(np.int8)

array_info(y)

ndim: 1
shape: (3,)
size: 3
dtype: int8
values:
[-1  2  3]



In [79]:
z = np.uint16(x)

array_info(z)

ndim: 1
shape: (3,)
size: 3
dtype: uint16
values:
[65535     2     3]



## Concatenation of arrays


In [80]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

result = np.concatenate([x, y])

array_info(result)

ndim: 1
shape: (6,)
size: 6
dtype: int32
values:
[1 2 3 3 2 1]



In [81]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

array_info(grid)

ndim: 2
shape: (2, 3)
size: 6
dtype: int32
values:
[[1 2 3]
 [4 5 6]]



In [82]:
result = np.concatenate([grid, grid])

array_info(result)

ndim: 2
shape: (4, 3)
size: 12
dtype: int32
values:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]



In [83]:
result = np.concatenate(
    [grid, grid],
    axis=0,
)

array_info(result)

ndim: 2
shape: (4, 3)
size: 12
dtype: int32
values:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]



In [84]:
result = np.concatenate(
    [grid, grid],
    axis=1,
)

array_info(result)

ndim: 2
shape: (2, 6)
size: 12
dtype: int32
values:
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]



In [85]:
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6], [7, 8, 9]])

result = np.vstack([x, grid])

array_info(result)

ndim: 2
shape: (3, 3)
size: 9
dtype: int32
values:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [86]:
y = np.array([[-1], [-1]])

result = np.hstack([grid, y])

array_info(result)

ndim: 2
shape: (2, 4)
size: 8
dtype: int32
values:
[[ 4  5  6 -1]
 [ 7  8  9 -1]]

