In [1]:
from collections.abc import Iterable

import numpy as np

# Numpy ufuncs


A universal function is a function:

-   that operates on ndarrays in an element-by-element fashion

A ufunc is a “vectorized” wrapper for a function that takes  
a fixed number of specific inputs and produces a fixed number of specific outputs.


In [2]:
np.random.seed(0)

## Native Python Loops


In [3]:
def reciprocal(
    values: Iterable[float],
) -> Iterable[float]:
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [4]:
small_array = np.random.randint(
    low=1,
    high=10,
    size=5,
)
print(reciprocal(small_array))

[0.16666667 1.         0.25       0.25       0.125     ]


| Fraction (sec) | Unit       | Symbol | Definition              | Comparative examples & common units        |
| -------------- | ---------- | ------ | ----------------------- | ------------------------------------------ |
| $10^{−9}$      | 1 nanosec  | ns     | One billionth of a sec  | One machine cycle by a 1 GHz processor 1ns |
| $10^{−6}$      | 1 microsec | µs     | One millionth of a sec  | One machine cycle by an Intel 80186 2.2 µs |
| $10^{−3}$      | 1 millisec | ms     | One thousandth of a sec | Human brain to fire one impulse 4–8 ms     |


In [5]:
small_array = np.random.randint(
    low=1,
    high=10,
    size=5,
)

%timeit reciprocal(small_array)

6.66 µs ± 770 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
big_array = np.random.randint(
    low=1,
    high=10,
    size=100_000,
)

%timeit reciprocal(big_array)

116 ms ± 4.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
200 * 1000 / 11.8

16949.15254237288

## Introducing UFuncs


In [8]:
print(reciprocal(small_array))
print(1.0 / small_array)

[0.25       0.16666667 0.33333333 0.2        0.125     ]
[0.25       0.16666667 0.33333333 0.2        0.125     ]


In [9]:
%timeit (1.0 / big_array)

82.3 µs ± 274 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
%timeit np.reciprocal(big_array)

86.9 µs ± 324 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
200 * 1000 / 103  # Speedup

1941.7475728155339

In [12]:
x = np.arange(4)

print(x)

[0 1 2 3]


In [13]:
print(x + 2)
print(x - 2)
print(x * 2)
print(x / 2)

[2 3 4 5]
[-2 -1  0  1]
[0 2 4 6]
[0.  0.5 1.  1.5]


In [14]:
print(x + 2.0)
print(x - 2.0)
print(x * 2.0)
print(x / 2.0)

[2. 3. 4. 5.]
[-2. -1.  0.  1.]
[0. 2. 4. 6.]
[0.  0.5 1.  1.5]


In [15]:
print(np.add(x, 2))

[2 3 4 5]


| Name       | Description                                                   |
| ---------- | ------------------------------------------------------------- |
| add        | Adds, element-wise                                            |
| subtract   | Subtracts, element-wise                                       |
| multiply   | Multiplies, element-wise                                      |
| matmul     | Matrix product of two arrays                                  |
| divide     | Returns a true division of the inputs, element-wise           |
| negative   | Numerical negative, element-wise                              |
| positive   | Numerical positive, element-wise                              |
| mod        | Return, element-wise remainder of division                    |
| absolute   | Calculate the absolute value, element-wise                    |
| fabs       | Compute the absolute values, element-wise                     |
| sign       | Returns an, element-wise indication of the sign of a number   |
| exp        | Calculate the exponential of all elements in the input array  |
| log        | Natural logarithm, element-wise                               |
| sqrt       | Return the non-negative square-root of an array, element-wise |
| square     | Return the, element-wise square of the input                  |
| reciprocal | Return the reciprocal of the argument, element-wise           |
| gcd        | Returns the greatest common divisor of \|x1\| and \|x2\|      |
| lcm        | Returns the lowest common multiple of \|x1\| and \|x2\|       |


In [16]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [17]:
print(np.abs(x))

[2 1 0 1 2]


In [18]:
print(np.fabs(x))

[2. 1. 0. 1. 2.]


In [19]:
x = np.array(
    [-2, -1, 0, 1, 2],
    dtype=np.float32,
)

print(np.abs(x))
print(np.fabs(x))

[2. 1. 0. 1. 2.]
[2. 1. 0. 1. 2.]


### Trigonometric functions


| Name | Description                      |
| ---- | -------------------------------- |
| sin  | Trigonometric sine, element-wise |
| cos  | Cosine, element-wise             |
| tan  | Compute tangent, element-wise    |


In [20]:
theta = np.linspace(
    start=0.0,
    stop=2.0 * np.pi,
    num=7,
)

print(theta)

[0.         1.04719755 2.0943951  3.14159265 4.1887902  5.23598776
 6.28318531]


In [21]:
print(np.sin(theta))
print(np.cos(theta))

[ 0.00000000e+00  8.66025404e-01  8.66025404e-01  1.22464680e-16
 -8.66025404e-01 -8.66025404e-01 -2.44929360e-16]
[ 1.   0.5 -0.5 -1.  -0.5  0.5  1. ]


### Bit-twiddling functions


| Name        | Description                                          |
| ----------- | ---------------------------------------------------- |
| bitwise_and | Compute the bit-wise AND of two arrays, element-wise |
| bitwise_or  | Compute the bit-wise OR of two arrays, element-wise  |
| bitwise_xor | Compute the bit-wise XOR of two arrays, element-wise |


In [25]:
np.bitwise_and(14, 13)

12

In [26]:
np.binary_repr(12)

'1100'

In [27]:
np.bitwise_and([14, 3], 13)

array([12,  1], dtype=int32)

### Comparison functions


| Name          | Description                                        |
| ------------- | -------------------------------------------------- |
| greater       | Return the truth value of (x1 > x2), element-wise  |
| greater_equal | Return the truth value of (x1 >= x2), element-wise |
| less          | Return the truth value of (x1 < x2), element-wise  |
| less_equal    | Return the truth value of (x1 <= x2), element-wise |
| not_equal     | Return (x1 != x2), element-wise                    |
| equal         | Return (x1 == x2), element-wise                    |


In [23]:
print(np.greater([4, 2], [2, 2]))

[ True False]


In [24]:
a = np.array([4, 2])
b = np.array([2, 2])

print(a > b)

[ True False]
