In [41]:
import numpy as np

# Numpy Broadcasting


In [42]:
np.random.seed(0)

The term broadcasting describes how numpy treats arrays with diff shapes during arith. operations.  
The smaller array is “broadcast” across the larger array so that they have compatible shapes.  
Broadcasting provides vectorizing array operations so that looping occurs in C instead of Python.  
If the dimensions are not compatible, you will get a ValueError

![broadcast](../media/np_multiply_broadcasting.png)

In the simplest example of broadcasting, the scalar `b` is stretched to become an array of  
with the same shape as `a` so the shapes are compatible for element-by-element multiplication.


In [43]:
a = np.array([1, 2])
b = 1.6

print(a * b)

[1.6 3.2]


In [44]:
print(a + 5)

[6 7]


In [45]:
M = np.ones(shape=(2, 2))

print(M)

[[1. 1.]
 [1. 1.]]


In [46]:
print(M + a)

[[2. 3.]
 [2. 3.]]


In [47]:
a = np.arange(
    start=0,
    stop=3,
)


b = np.arange(
    start=0,
    stop=3,
)[:, np.newaxis]


print(a)


print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [48]:
print(a + b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [49]:
M = np.ones(shape=(2, 3))
a = np.arange(
    start=0,
    stop=3,
    step=1,
)

print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [50]:
print(M + a)

[[1. 2. 3.]
 [1. 2. 3.]]


In [51]:
a = np.arange(
    start=0,
    stop=9,
    step=1,
).reshape((3, 3))


b = np.arange(
    start=0,
    stop=3,
    step=1,
)

In [52]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [53]:
print(b)

[0 1 2]


In [54]:
print(a + b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


### Standardization


In [55]:
x = np.random.normal(
    loc=5.0,
    scale=2.0,
    size=(100_000, 2),
)

In [56]:
x_mean = np.mean(
    x,
    axis=0,
)

In [57]:
print(x_mean)

[5.0001525  5.01318739]


In [58]:
x_var = np.var(
    x,
    axis=0,
)

In [59]:
print(x_var)

[3.98573966 3.98244747]


In [60]:
x_centered = x - x_mean

In [61]:
new_mean = np.mean(x_centered, axis=0)

In [62]:
print(new_mean)

[-4.44956250e-14 -3.04893977e-14]


In [63]:
print(np.equal(new_mean, 0.0))

[False False]


In [64]:
print(np.isclose(new_mean, 0.0))

[ True  True]


In [65]:
x_standardized = x_centered / (np.sqrt(1e-6 + x_var))

In [66]:
new_var = np.var(x_standardized, axis=0)

In [67]:
print(new_var)

[0.99999975 0.99999975]


In [68]:
print(np.equal(new_var, 1.0))

[False False]


In [69]:
print(np.isclose(new_var, 1.0))

[ True  True]
