# Array Masks


In [57]:
import numpy as np
from numpy import ma


np.random.seed(0)

## Recap: Comparison Operators


In [58]:
x = np.array([1, 2, 3, 4, 5])

In [59]:
print(x < 3)

[ True  True False False False]


In [60]:
print(x > 3)

[False False False  True  True]


In [61]:
print(x != 3)

[ True  True False  True  True]


In [62]:
print(x == 3)

[False False  True False False]


## Working with Boolean Arrays


In [63]:
print(x)

[1 2 3 4 5]


In [64]:
print(x < 5)

[ True  True  True  True False]


In [65]:
np.count_nonzero(x < 5)

4

In [66]:
np.sum(x < 5)

4

In [67]:
check = x < 4

In [68]:
print(check)

[ True  True  True False False]


In [69]:
print(check.astype(np.int8))

[1 1 1 0 0]


In [70]:
np.sum(check)

3

In [71]:
print(x < 10)

array([ True,  True,  True,  True,  True])

In [72]:
np.all(x < 10)

True

In [73]:
np.all(x == 6)

False

In [74]:
np.any(x >= 0)

True

### Boolean operators


In [75]:
x = np.random.uniform(
    low=-1.5,
    high=1.5,
    size=10,
)

In [76]:
print(x)

[ 0.14644051  0.6455681   0.30829013  0.13464955 -0.2290356   0.43768234
 -0.18723837  1.175319    1.39098828 -0.34967544]


In [77]:
print(True & True)

True


In [78]:
print(1 & 1)

1


In [79]:
print(x > 0.5)

[False  True False False False False False  True  True False]


In [80]:
print(x < 1)

[ True  True  True  True  True  True  True False False  True]


In [81]:
print((x > 0.5) & (x < 1))

[False  True False False False False False False False False]


In [82]:
np.sum((x > 0.5) & (x < 1))

1

In [83]:
print(x > 0.5)

[False  True False False False False False  True  True False]


In [84]:
print(x < 1)

[ True  True  True  True  True  True  True False False  True]


In [85]:
print((x > 0.5) | (x < 1))

[ True  True  True  True  True  True  True  True  True  True]


In [86]:
print(np.sum((x > 0.5) | (x < 1)))

10


In [87]:
print(np.sum(~((x <= 0.5) | (x >= 1))))

1


In [88]:
print(x)

[ 0.14644051  0.6455681   0.30829013  0.13464955 -0.2290356   0.43768234
 -0.18723837  1.175319    1.39098828 -0.34967544]


In [89]:
print(np.sum(x == 0))

0


In [90]:
print(np.sum(x != 0))

10


In [91]:
print(np.sum(x > 0.5))

3


In [92]:
print(np.sum((x > 0) & (x < 0.2)))

2


## Boolean Indexing


In [93]:
print(x)

[ 0.14644051  0.6455681   0.30829013  0.13464955 -0.2290356   0.43768234
 -0.18723837  1.175319    1.39098828 -0.34967544]


In [94]:
print(x.shape)

(10,)


In [95]:
print(x < 1.0)

[ True  True  True  True  True  True  True False False  True]


In [96]:
x_slice = x[x < 1.0]

In [97]:
print(x_slice)

[ 0.14644051  0.6455681   0.30829013  0.13464955 -0.2290356   0.43768234
 -0.18723837 -0.34967544]


In [98]:
print(x_slice.shape)

(8,)


# Numpy Masks

In many circumstances, datasets can be incomplete or include invalid data.  
For example, a sensor may have failed to record a data.  
The numpy.ma module provides a convenient way to address this by masked arrays.

A masked array is the combination of a standard numpy.ndarray and a mask.  
When an element of the mask is False:  
=> The corresponding element of the associated array is valid and is said to be unmasked.  
When an element of the mask is True:  
=> the corresponding element of the associated array is said to be masked (invalid).

| asarray              | Convert the input to a masked array of the given data-type.         |
| -------------------- | ------------------------------------------------------------------- |
| fix_invalid          | Return input with invalid data masked and replaced by a fill value. |
| masked_equal         | Mask an array where equal to a given value.                         |
| masked_greater       | Mask an array where greater than a given value.                     |
| masked_greater_equal | Mask an array where greater than or equal to a given value.         |
| masked_inside        | Mask an array inside a given interval.                              |
| masked_invalid       | Mask an array where invalid values occur (NaNs or infs).            |
| masked_less          | Mask an array where less than a given value.                        |
| masked_less_equal    | Mask an array where less than or equal to a given value.            |
| masked_not_equal     | Mask an array where not equal to a given value.                     |
| masked_where         | Mask an array where a condition is met.                             |


In [99]:
data = np.array([1, 2, 3, -1, 5])

In [100]:
masked_data = ma.masked_array(
    data,
    mask=[0, 0, 0, 1, 0],
)

In [101]:
print(masked_data)

[1 2 3 -- 5]


In [102]:
print(masked_data.mean())

2.75


In [103]:
masked_data2 = ma.masked_equal(
    [1.0, -1.0, 3.0, -1.0],
    value=-1.0,
)

In [104]:
print(masked_data2)

[1.0 -- 3.0 --]


In [105]:
masked_data3 = ma.masked_less_equal(
    [1.0, -1.0, 3.0, -1.0],
    value=1.0,
)

In [106]:
print(masked_data3)

[-- -- 3.0 --]


In [107]:
print(masked_data3[~masked_data3.mask])

[3.0]
