In [1]:
import numpy as np

# Save and Store Numpy Data


In [2]:
np.random.seed(0)

In [3]:
def structured_array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"names: {array.dtype.names}")
    print(f"fields: {array.dtype.fields}")
    print(f"values:\n{array}\n")

```python
numpy.save(
    file,
    arr,
    allow_pickle=True,
    fix_imports=True
)
```

Save an array to a binary file in NumPy .npy format.

```python
numpy.load(
    file,
    mmap_mode=None,
    allow_pickle=False,
    fix_imports=True,
    encoding='ASCII'
)
```

Load arrays or pickled objects from .npy, .npz or pickled files.

### Further functions

np.savez, np.savetxt, np.loadtxt

If you want to store a single ndarray object, store it as a .npy file using np.save.  
If you want to store more than one ndarray object in a single file, save it as a .npz file using np.savez.


In [4]:
with open("../data/test.npy", "wb") as f:
    np.save(f, np.zeros((1000, 100), dtype=np.int32))

In [5]:
with open("../data/test.npy", "rb") as f:
    a = np.load(f)

In [6]:
print(a)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Structured arrays

Structured arrays are ndarrays whose datatype is a composition of simpler datatypes organized as a sequence of named fields.

Structured datatypes are designed to be able to mimic ‘structs’ in the C language.  
They are meant for interfacing with C code and for low-level manipulation of structured buffers,  
for example for interpreting binary blobs.  
For these purposes they support specialized features such as subarrays,  
nested datatypes, and unions, and allow control over the memory layout of the structure.


In [7]:
x = np.array(
    [
        ("Jan", 9, 81.0),
        ("Peter", 3, 27.0),
    ],
    dtype=[
        ("name", "U10"),
        ("age", "i4"),
        ("weight", "f4"),
    ],
)

In [8]:
structured_array_info(x)

ndim: 1
shape: (2,)
size: 2
dtype: [('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]
names: ('name', 'age', 'weight')
fields: {'name': (dtype('<U10'), 0), 'age': (dtype('int32'), 40), 'weight': (dtype('float32'), 44)}
values:
[('Jan', 9, 81.) ('Peter', 3, 27.)]

