In [1]:
import numpy as np

# Several Important Numpy Functions


In [2]:
np.random.seed(0)

In [3]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

In [4]:
def compare_arrays(
    a1: np.ndarray,
    a2: np.ndarray,
) -> None:
    print(a1)
    print(a2)

In [5]:
x = np.arange(4).reshape((2, 2))

array_info(x)

ndim: 2
shape: (2, 2)
size: 4
dtype: int32
values:
[[0 1]
 [2 3]]



## Axis Related Functions


np.moveaxis(a, sources, destinations):

This function can be used to rearrange specific dimensions of an array.


In [6]:
x_moved = np.moveaxis(
    x,
    source=0,
    destination=1,
)

compare_arrays(
    x,
    x_moved,
)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


np.transpose(a, axes=None):

This function can be used to rearrange all dimensions of an array at once.


In [7]:
x_transposed = np.transpose(x)

compare_arrays(
    x,
    x_transposed,
)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [8]:
x_transposed = x.T

compare_arrays(
    x,
    x_transposed,
)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [9]:
x_rolled = np.roll(
    x,
    axis=0,
    shift=-1,
)

compare_arrays(x, x_rolled)

[[0 1]
 [2 3]]
[[2 3]
 [0 1]]


In [10]:
x_rolled = np.roll(
    x,
    axis=1,
    shift=-1,
)

compare_arrays(x, x_rolled)

[[0 1]
 [2 3]]
[[1 0]
 [3 2]]


## Indexing


In [11]:
idxs = np.indices((2, 2))

print(idxs)

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


In [12]:
idxs = np.diag_indices(2)

print(idxs)

(array([0, 1]), array([0, 1]))


In [13]:
idxs = np.tril_indices(2)

print(idxs)

(array([0, 1, 1]), array([0, 0, 1]))


In [14]:
idxs = np.triu_indices(2)

print(idxs)

(array([0, 0, 1]), array([0, 1, 1]))


In [15]:
c = x >= 2
w = np.where(c)

In [16]:
print(c)

[[False False]
 [ True  True]]


In [17]:
print(x)

[[0 1]
 [2 3]]


In [18]:
print(w)

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))


In [19]:
print(x[w])

[2 3]


## Sorting


In [20]:
y = np.random.randint(
    low=-10,
    high=10,
    size=10,
)

array_info(y)

ndim: 1
shape: (10,)
size: 10
dtype: int32
values:
[  2   5 -10  -7  -7  -3  -1   9   8  -6]



In [21]:
y_sorted = np.sort(y)

compare_arrays(y, y_sorted)

[  2   5 -10  -7  -7  -3  -1   9   8  -6]
[-10  -7  -7  -6  -3  -1   2   5   8   9]


In [22]:
y_sorted = np.argsort(y)

compare_arrays(y, y_sorted)

[  2   5 -10  -7  -7  -3  -1   9   8  -6]
[2 3 4 9 5 6 0 1 8 7]


In [23]:
y_argmax = np.argmax(y)

print(y_argmax)

7


In [24]:
y_argmin = np.argmin(y)

print(y_argmin)

2
