In [1]:
import numpy as np

# Exercise


In [2]:
np.random.seed(0)

In [3]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

## Exercise 1

-   Create an array M of shape (3, 3) with zeros at all entries
-   Fill the diagonal values with np.pi
-   Fill the upper triangular (except the diag) with 1
-   Fill the lower triangular (except the diag) with -1

The resulting matrix should have the following values:

```python
[[ 3.14159265  1.          1.        ]
 [-1.          3.14159265  1.        ]
 [-1.         -1.          3.14159265]]
```


In [4]:
M = np.zeros(shape=(3, 3))

print(M)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
idxs = np.diag_indices(n=3)
M[idxs] = np.pi

(array([0, 1, 2]), array([0, 1, 2]))
[[3.14159265 0.         0.        ]
 [0.         3.14159265 0.        ]
 [0.         0.         3.14159265]]


In [ ]:
print(idxs)

In [ ]:
print(M)

In [6]:
def upper_tri_indexing(
    M: np.ndarray,
) -> tuple:
    return np.triu_indices(M.shape[0], 1)

In [7]:
def lower_tri_indexing(
    M: np.ndarray,
) -> tuple:
    return np.tril_indices(M.shape[0], -1)

In [8]:
idxs = upper_tri_indexing(M)
M[idxs] = 1

In [9]:
print(idxs)

(array([0, 0, 1]), array([1, 2, 2]))


In [10]:
print(M)

[[3.14159265 1.         1.        ]
 [0.         3.14159265 1.        ]
 [0.         0.         3.14159265]]


In [11]:
idxs = lower_tri_indexing(M)
M[idxs] = -1

In [12]:
print(idxs)

(array([1, 2, 2]), array([0, 0, 1]))


In [13]:
print(M)

[[ 3.14159265  1.          1.        ]
 [-1.          3.14159265  1.        ]
 [-1.         -1.          3.14159265]]


## Exercise 2

-   Get the indicies where the matrix values are greater than or equal to one


In [14]:
idxs = np.where(M >= 0)

In [15]:
print(idxs)

(array([0, 0, 0, 1, 1, 2], dtype=int64), array([0, 1, 2, 1, 2, 2], dtype=int64))


In [16]:
boolean = M >= 0
idxs = np.nonzero(boolean)

In [17]:
print(idxs)

(array([0, 0, 0, 1, 1, 2], dtype=int64), array([0, 1, 2, 1, 2, 2], dtype=int64))
